development:
#  sessions:
#    default:
#      database: mongoid_workshop
#      hosts:
#        - localhost:27017

test:
#  sessions:
#    default:
#      database: mongoid_workshop_test
#      hosts:
#        - localhost:27017
