#!/usr/bin/env ruby
ENV['MONGOID_ENV'] = 'development'
require './init'

User.create(
  :name => 'Martin',
  :properties => [
    Property.new(:name => 'Villa Schonenburg'),
    Property.new(:name => 'Villa Schonenblitz')
  ])

User.create(
  :name => 'George',
  :properties => [
    Property.new(:name => 'Acropolis')
  ])

Delayed::Job.create({ attempts: 4, priority: 1400, run_at: Time.now, failed_at: Time.now, handler: "--- !ruby/object:OpportunitiesObserver::UserUpdater \ncallback: :after_create\n" })
Delayed::Job.create({ handler: "--- !ruby/struct:Paperclip::Storage::S3::DeleteJob \npaths: {}\n\ns3_params: \n", priority: 100, attempts: 0 })
Delayed::Job.create({ handler: "--- !ruby/struct:Paperclip::Storage::S3::DeleteJob \npaths: {}\n\ns3_params: \n", priority: 100, attempts: 0 })
Delayed::Job.create({ handler: "--- !ruby/struct:Paperclip::Storage::S3::DeleteJob \npaths: {}\n\ns3_params: \n", priority: 100, attempts: 0 })
Delayed::Job.create({ handler: "--- !ruby/struct:Paperclip::Storage::S3::DeleteJob \npaths: {}\n\ns3_params: \n", priority: 100, attempts: 0 })
Delayed::Job.create({ handler: "--- !ruby/struct:Paperclip::Storage::S3::DeleteJob \npaths: {}\n\ns3_params: \n", priority: 100, attempts: 0 })
Delayed::Job.create({ handler: "--- !ruby/struct:Paperclip::Storage::S3::DeleteJob \npaths: {}\n\ns3_params: \n", priority: 100, attempts: 0 })
